parameters:
#    etitcEncuestas.example.class: etitc\EncuestasBundle\Example

services:
#    etitcEncuestas.example:
#        class: %etitcEncuestas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
