entecontrol_list:
    pattern:  /list
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:list" }
    
entecontrol_show:
    pattern:  /{id}/show
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:show" }
    
entecontrol_new:
    pattern:  /new
    defaults: { _controller: "SECSolicitudesBundle:EnteControl:new" }
    
entecontrol_create:
    pattern:  /create
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:create" }
    requirements: { _method: post }
    
entecontrol_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:edit" }
    
entecontrol_update:
    pattern:  /{id}/update
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:update" }
    requirements:  { _method: post }
   
entecontrol_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SECSolicitudesBundle:Entecontrol:delete" }
    requirements: { _method: post }
    
