<?php

namespace SEC\SolicitudesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionRepository extends EntityRepository
{
}
