<?php

namespace SEC\SolicitudesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnteControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnteControlRepository extends EntityRepository
{
}
